# Generated by Django 2.1.7 on 2019-07-14 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus', '0049_auto_20190529_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosinnusgroup',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, blank=True, null=True),
        ),
    ]
